name: Pylint

# TODO: Only run this workflow against certain branches to save time? Maybe on PR?
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Copied from: https://github.com/marketplace/actions/pylint-with-dynamic-badge
      - uses: Silleellie/pylint-github-action@v2.1
        with:
          lint-path: |
            app
            scripts
          python-version: '3.10'
          requirements-path: requirements.txt
          readme-path: README.md
          pylintrc-path: .pylintrc
          badge-text: PyLint
          color-bad-score: red
          color-ok-score: orange
          color-good-score: yellow
          color-perfect-score: brightgreen